config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  	root "projects#index"

	get "/projects", to: "projects#index"

	resources :projects, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :file, attachment: true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact from heatherallaman.com",
      :to => "heather.allaman@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :project_due

  attribute :file_upload, attachment: true, validate: :ok_format?

  attribute :nickname,  :captcha  => true

  def ok_format?
    unless file_upload.nil?
      ext = File.extname(file_upload)

      if !%w( .jpg .jpeg .png .pdf .bmp .eps .docx .doc .tiff .ai .psd .raw .xd .dng ).include? ext.downcase 
        self.errors.add(:file_upload, ext + " not a valid file type. Only images, PDFs, and design files allowed.")
      end
    end
  end

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => %(#{name} wants to collaborate),
      :to => "heather.allaman@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @contact = Project.new(params[:project])
  end

  def create
    @contact = Project.new(params[:project])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Project.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-5 py-3">
  <%= link_to image_tag("Heather_Allaman_Logo_Violet.png", :class => 'navbar-brand logo'), root_path %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarT" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbar">
    <ul class="navbar-nav mr-1 mt-2 mt-lg-0  justify-content-end text-right">
      <li class="nav-item">
        <%= link_to 'PROJECTS', projects_path(anchor: 'work'), :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'ABOUT', projects_path(anchor: 'about'), :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'CONTACT', projects_path(anchor: 'contact'), :class => 'nav-link' %>
    </ul>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload'%>

  </head>

  
  <%= render partial: 'layouts/header' %>

  <div class="container-fluid"> 
    <%= yield %>
  </div>
</html>

app/views/projects/_contact_form.html.erb
      
<div class="text-center col-sm-6 align-self-center m-auto" id="flash-message">
    <%= render 'flash' %>
</div>

<%= simple_form_for @contact, url: projects_path, remote: true, :html => {:mulitpart => true, :class => 'form-horizontal pt-2 col-sm-6 align-self-center m-auto'} do |f| %>
    
    <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <%= f.input :name, placeholder: "Name", required: true, error: 'Please include your name' %>

        <%= f.input :email, placeholder: "Email", required: true, error: 'Please use a valid email address' %>

        <%= f.input :message, rows: 8, cols: 40, required: true, 
                          placeholder: "Tell me a little about your project", as: :text %>

        <%#= f.input :project_due, as: :date, start_year: Date.today.year,
                              end_year: Date.today.year + 2, 
                              order: [:month, :day, :year], html5: true %>
        <%= f.input :project_due, as: :date, :input_html => { :value => DateTime.now.strftime("%d/%m/%Y")},  html5: true%>

        <%= f.input :file_upload, as: :file, input_html: { label: "Upload images, pdfs, or design files" } %>


        <div class= "hidden">
          <%= f.label :nickname %>
          <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
        </div>

      <%= f.submit 'SEND IT', class: 'btn ha-btn' %>
<% end %>

  

app/views/projects/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:h3, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/projects/create.js.erb
// Test for ajax success
//console.log("This is the create.js.erb file");

// Render flash message
$('#contact-form').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/projects/index.html.erb
<div class="welcome">

	<div id="home_header">

	</div>

	<div class="work-header">
		<div class="row">
			<div class="col mx-auto">
				<h3 class="text-center">Development for designers</h3>
			</div>
		</div>
	</div>

	<div class="lead py-4">

		<div class="row align-items-start d-flex py-5">

			<div class="col-sm-12 col-md-3 justify-content-sm-start justify-content-lg-end text-right">
				<h2 class="side">Webflow + </h2>
				<h2 class="side">Shopify + </h2>
				<h2 class="side">Squarespace +</h2>
			</div>

			<div class="entry col-sm-12 col-md-8 text-left border-left">
				<div class="text-left blurb">
					<h1>Bringing your designs to life</h1>
					<h2>Need help getting your designs online?</h2>

					<p>I work with designers who need a skilled developer to get the job done. With solid communication at the forefront, working with me means working efficiently. </p>

					<p>Getting your designs on Shopify and Squarespace platforms can be challenging. You might find it's:</p>
					<p><ul class="text-left">
						<li>time consuming to figure out the details</li>
						<li>not the best use of your skills</li>
						<li>frustrating to work within in the limits of a template</li>
					</ul></p>
			
				</div>

			</div>
		</div>
	</div>




	

	

	<div class="m-5 mb-0 p-2 pt-3 pb-0" id="work">
		<div class="row d-flex flex-wrap">
			<div class="col-xs-12 col-md-4 text-center px-3 pb-5">
				<a href="https://www.westchestertherapy.com" target="_blank">
					<%= image_tag 'wt.png', class: 'img-thumbnail img-fluid' %>
				</a>
				<div class="align-self-center text-left info">
					<h1>WESTCHESTER THERAPY</h1>
					<h2>Webflow</h2>
					
					<p >Designed by <a href="http://www.goodready.co" target="_blank">Good + Ready Design Co.</a></p>
				</div>
			</div>
			<div class="col-xs-12 col-md-4 text-center px-3 pb-5">
				<a href="https://www.sweetthornflora.com" target="_blank">
					<%= image_tag 'stf.png', class: 'img-thumbnail img-fluid' %>
				</a>
				<div class="align-self-center text-left info">
					<h1>SWEET THORN FLORA</h1>
					<h2>Squarespace</h2>
					
					<p >Designed by <a href="http://www.goodready.co" target="_blank">Good + Ready Design Co.</a></p>
				</div>
			</div>
		
			<div class="col-xs-12 col-md-4 text-center px-3 pb-5">
				<a href="https://island-house-ky.myshopify.com/" target="_blank">
					<%= image_tag 'island.png', class: 'img-thumbnail img-fluid' %>
				</a>
				<div class="align-self-center text-left info">
					<h1>ISLAND HOUSE</h1>
					<h2>Shopify</h2>
					
					<p >Designed by <a href="http://www.goodready.co" target="_blank">Good + Ready Design Co.</a></p>
					
				</div>
			</div>

			<div class="col-xs-12 col-md-4  text-center px-3 pb-5">
				<a href="http://arroyodesignhouse.com" target="_blank">
					<%= image_tag 'arroyo.png', class: 'img-thumbnail img-fluid' %>
				</a>
				<div class="align-self-center text-left info">
					<h1>ARROYO DESIGN HOUSE</h1>
					<h2>Built with Javascript</h2>
					<p>Portfolio site.</p>
				</div>
			</div>
		
		
			<div class="col-xs-12 col-md-4  text-center px-3 pb-5">
				<a href="https://heathersmoonblog.herokuapp.com/blog" target="_blank">
					<%= image_tag 'mvg.png', class: 'img-thumbnail img-fluid' %>
				</a>
				<div class="align-self-center text-left info">
					<h1>MOON BLOG</h1>
					<h2>Built with Rails</h2>
					<p>Customizable membership site.</p>
				</div>
			</div>

			

			<div class="col-xs-12 col-md-4 text-center mx-auto"></div>


		</div>
	</div>

		<div class="solution lead">

		<div class="row align-items-start d-flex py-5">

			<div class="col-sm-12 col-md-3 justify-content-sm-start justify-content-lg-end text-right">
				<h2 class="side">how I can help +</h2>
			</div>

			<div class="entry col-sm-12 col-md-8 text-left border-left-egg">
				<div class="text-left blurb">
					<h1>Creating more time for you</h1>

					<h2>Working with me lends you more:</h2>

					<ul class="text-left">

						<li class="pb-3">freedom to design for the look you want</li>
						<li class="pb-3">confidence that your site won't look like others</li>
						<li class="pb-0">time to focus on the work you do best </li>

					</ul>
				</div>

			</div>
		</div>

		<!--<div class="row align-items-start d-flex justify-content-center p-5">

			<div class="entry col-sm-12 col-md-7 text-center justify-content-center">
				<div class="text-center blurb mx-auto">
					<h1>How I Can Help</h1>

					<p class="px-0 pb-0 mx-0"><ul class="center-this">

						<li class="pb-3">have freedom to design for the look you want</li>
						<li class="pb-3">have confidence that your site won't look like others</li>
						<li class="pb-0">have time to focus on the work you do best </li>

					</ul></p>

			
				</div>

			</div>

		</div>-->
	</div>

	<div class="row callout">
		<div class="col text-center button mx-auto p-5">
			<h4>Are you ready to bring ease back into your workflow?</h4>

			<%= link_to "LET'S COLLABORATE", projects_path(anchor: 'contact'), class: "btn btn-default ha-btn" %>

		</div>	
	</div>

	<div class="testimonial">
		<div class="row p-5">
			<div class="col mx-auto my-3">
				<h3 class="text-center mx-auto">Heather is hands-down my favorite developer as she's simply the easiest person to work with. From a communication perspective -- you'd be hard-pressed to find a more intuitive, thoughtful and caring person out there. She anticipated our project needs at every stage of production while keeping her eye on the big picture. This attention to detail and future state problem solving resulted in a beautiful and perfectly functioning end project. <!--My husband and I were thrilled with the work she did on our website and have always felt supported beyond its launch -- whether with a copy update or in adding new products. I absolutely can't say enough about Heather and would not hesitate to recommend her work to anyone.--></h3>
				<p></p>
				<h3 class="text-center pb-0 mx-auto">- Katie J., <a href="http://www.arroyodesignhouse.com" target="_blank">Arroyo Design House</a> </h3>	
			</div>	
		</div>
	</div>
	

	<div id="about" class="row d-flex justify-content-center p-5">

		<div class="col-xs-12 col-sm-4 justify-content-xs-center justify-content-sm-end pr-0">
			<div class="thumbnail">
				<%= image_tag 'pic.jpg' %>
			</div>
		</div>

		<div class="col-xs-12 col-sm-4 text-left justify-content-xs-center justify-content-sm-start pl-0 mt-4">
			<h2>Hi, I'm HEATHER</h2>
			<p>I'm passionate about all things front end, and I love the process of bringing flat files to life on the web. I strive to listen well and preempt problems before they arise. </p>
		</div>

	</div>

	<div id="contact">
		<div class="row p-3">
			<div class="col text-center justify-content-center" id="contact-form">
			<div class="row p-5">
			<div class="col-sm-6 mx-auto text-center">
				<h1 class="text-center">WRITE ME</h1>
				<p class="text-center">If you think we could be a good fit for you next project, please get in touch!</p>
			</div>
			</div>
			<%= render 'contact_form' %>
			</div>			

		</div>
		<div class="row p-5">
			<p class="text-left d-flex align-self-center">
				<span class="align-self-end">made with </span>
				<a href="http://www.linux.org"><i class="fab fa-linux fa-3x px-2"></i></a>
				
				<i class="fas fa-plus align-self-center"></i>
				<a href="http://www.ubuntu.com"><i class="fab fa-ubuntu fa-3x px-2"></i></a>

				<i class="fas fa-plus align-self-center"></i>
				<a href="http://www.github.com/hallaman"><i class="fab fa-github fa-3x px-2"></i></a>
			</p>
			<p class="text-right col">copyright <%= Time.now.year %>. Heather Allaman, all rights reserved</p>
	
		</div>

	</div>